version: '3.1'

services:
  web:
    build: .
    ports:
      - '9000:9000'
    env_file:
      - ./server/.env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=cheaphouses
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
