version: '3.1'

services:
  web:
    build: .
    ports:
      - '9000:9000'
    env_file:
      - ./server/.env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  migrations:
    container_name: run_migrations
    env_file:
      - ./server/.env
    build: ./
    command: npm run db:migrate:latest
    depends_on:
      - postgresdb

