name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client_lint:
    runs-on: ubuntu-latest
    name: Client Lint
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: cd client && npm install

    - name: run lint
      run: cd client && npm run lint

  client_test:
    runs-on: ubuntu-latest
    name: Client Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm install
        run: cd client && npm install

      - name: run test
        run: cd client && npm run test

  server_lint:
    runs-on: ubuntu-latest
    name: Server Lint
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: cd server && npm install

    - name: run lint
      run: cd server && npm run lint

  server_build:
    runs-on: ubuntu-latest
    name: Server Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: cd server && npm install

    - name: run build
      run: cd server && npm run build
