name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: NPM install
        uses: npm i

      - name: Lint
        run: npm run lint
