name: Deploy

on:
  push:
    branches:
      - prod
      - main

jobs:
  deploy:
    env:
      BUILD_ENV: prod
      POSTGRES_HOST: ${{ secrets.PROD_POSTGRES_HOST }}
      POSTGRES_USER: ${{ secrets.PROD_POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.PROD_POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.PROD_POSTGRES_DB }}
    runs-on: ubuntu-latest
    name: Deploy to Prod
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        export_default_credentials: true
    - run: gcloud info

    - name: Build docker image
      env:
        DOCKER_BUILDKIT: 1
      run: make docker-build

    - name: Push docker image
      run: make docker-push

    - name: Deploy to Cloud Run
      run: make docker-deploy
